name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Use cached node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: pnpm lint
        env:
          CI: true

      - name: Test
        run: pnpm test:run --coverage --maxWorkers=2
        env:
          CI: true

      - name: Build
        run: pnpm build
        env:
          CI: true
